# Generated by Django 3.0.5 on 2021-09-29 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210929_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='measurements_unit',
            new_name='measurement_unit',
        ),
    ]
